import math

print('Round 1.5    : ', round(1.5))
print('Floor 1.5    : ', math.floor(1.5))
print('Ceil  1.5    : ', math.ceil(1.5))
print('Pi value     : ',math.pi)
print('E  value     : ',math.e)
print('Sin(Pi/2)    : ', math.sin(math.pi / 2)) #Radians numbers
print('Sin(Pi)      : ', math.sin(math.pi))
print('Round Sin(Pi): ', round(math.sin(math.pi)))
print('Cos(0)       : ', math.cos(0))
print('Arcsin(0)    : ', math.asin(0))
print('Arccos(1)    : ', math.acos(1))
print('Arccos(0)    : ', math.acos(0))
print('Hypot(3,4)   : ', math.hypot(3,4))
print('2**3         : ', 2**3)
print('Pow(2,3)     : ', math.pow(2,3))
print('e**2         : ', math.e ** 2)
print('Exp(2)       : ', math.exp(2))
print('Log(e)       : ', math.log(math.e))
print('log10(1000)  : ', math.log10(1000))
print('log2(8)      : ', math.log2(8))
